TRUNCATE TABLE public.cost_center RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.employee RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.head_count RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.job_request RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.lever RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.location RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.optim_user RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.ppsid RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.purchase_orders RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.siglum RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.workload RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.workload_evolution RESTART IDENTITY CASCADE;


DROP TABLE IF EXISTS public.employee_test CASCADE;
DROP TABLE IF EXISTS public.employee_test_nifi CASCADE;
DROP TABLE IF EXISTS public.job_request_test CASCADE;
DROP TABLE IF EXISTS public.lever_test CASCADE;
DROP TABLE IF EXISTS public.purchase_orders_test CASCADE;