spring:
  application:
    name: optim

  datasource:
    url: jdbc:postgresql://db:5432/mydb
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  mvc:
    servlet:
      path: /api/optim

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

scheduled:
  fixedRate: 3000000

springdoc:
  swagger-ui:
    tags-sorter: alpha
